# Generated by Django 4.0.3 on 2024-04-22 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_servicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='descriptionn',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='descriptionnn',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='descriptionnnn',
        ),
    ]
